version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: integration.dockerfile
    ports:
      - "8001:8000"
    networks:
      - integration-net

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    networks:
      - integration-net

volumes:
  ollama-data:

networks:
  integration-net:
    driver: bridge